#!/bin/bash

commands=("Birthdate Calculator" "Calendar Calculator" "Date Calculator" "Master Number Name Generator" "Quit")

selected=0

# Function to display the list and highlight the selected item
display_list() {
    clear
    echo -e "\033[1m  Numerology Calculator\033[0m\n  ---------------------"
    for i in "${!commands[@]}"; do
        if [ $i -eq $selected ]; then
            if [ "${commands[$i]}" == "Quit" ]; then
                echo -e "\033[1m➤ ${commands[$i]}\033[0m\n"
            else
                echo -e "\033[1m➤ ${commands[$i]}\033[0m\n"
            fi
        else
            echo -e "  ${commands[$i]}\n"
        fi
    done
}

# Function to execute the selected command
execute_command() {
    case ${commands[$selected]} in
        "Birthdate Calculator") 
            python3 /home/user/Files/GitHub/Numerology-Calculator/calculators/birthdate-calculator.py
            read -p "Press Enter to return to the menu..."
            ;;
        "Calendar Calculator") 
            python3 /home/user/Files/GitHub/Numerology-Calculator/calculators/calendar-calculator.py
            read -p "Press Enter to return to the menu..."
            ;;
        "Date Calculator") 
            python3 /home/user/Files/GitHub/Numerology-Calculator/calculators/date-calculator.py
            read -p "Press Enter to return to the menu..."
            ;;
        "Master Number Name Generator") 
            python3 /home/user/Files/GitHub/Numerology-Calculator/calculators/master-number-name-generator.py
            read -p "Press Enter to return to the menu..."
            ;;
        "Quit") 
            echo -e "\n\033[1mExiting script\033[0m"
            exit 0
            ;;
        *) 
            echo -e "\nInvalid selection"
            ;;
    esac
}

# Main loop
while true; do
    display_list

    read -sn 1 key

    case $key in
        "A") ((selected--)); [ $selected -lt 0 ] && selected=$(( ${#commands[@]} - 1 ));;
        "B") ((selected++)); [ $selected -ge ${#commands[@]} ] && selected=0 ;;
        "") execute_command ;;
        *) ;;
    esac
done
